package aim4.gui.frame.signalvisualization;

import aim4.config.ringbarrier.RingAndBarrier;
import aim4.gui.Viewer;
import java.awt.Rectangle;
import javax.swing.JFrame;

//todo, clean this up. Sorry to anyone coming back to read this, Swing was deprecated before I got to this. So I've spen almost no time learning it. I'm also only doing this one frame, so I didn't spend the time to mix JFX into this.
//todo, also, add a scroll bar for the rings (here/SignalVisualizationPanel?) in case someone has a TOOOON of rings
/**
 * The vehicle information frame.
 */
@SuppressWarnings("serial")
public final class SignalVisualizationWindow extends javax.swing.JFrame {

    /**
     * Creates new form SignalVisualizationFrame
     *
     * @param viewer
     * @param secondsToSupport
     */
    public SignalVisualizationWindow(Viewer viewer, float secondsToSupport) {
        setTitle("AIM Sim Signal " + secondsToSupport + "s Historical Analysis");
        initComponents();
        Rectangle rect = viewer.getBounds();
        this.setLocation((int) rect.getMaxX() + 1, (int) rect.getMinY());
        signalVisualizationPanel1.initialize(viewer, secondsToSupport);
    }

    public void setRingAndBarrier(RingAndBarrier rb) {
        signalVisualizationPanel1.setRingAndBarrier(rb);
    }
    
    public void updateCurrentPhaseSegmentDepictions() {
        signalVisualizationPanel1.updateCurrentPhaseSegmentDepictions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signalVisualizationPanel1 = new aim4.gui.frame.signalvisualization.SignalVisualizationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout signalVisualizationPanel1Layout = new javax.swing.GroupLayout(signalVisualizationPanel1);
        signalVisualizationPanel1.setLayout(signalVisualizationPanel1Layout);
        signalVisualizationPanel1Layout.setHorizontalGroup(
            signalVisualizationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        signalVisualizationPanel1Layout.setVerticalGroup(
            signalVisualizationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalVisualizationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalVisualizationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aim4.gui.frame.signalvisualization.SignalVisualizationPanel signalVisualizationPanel1;
    // End of variables declaration//GEN-END:variables
}
